### PR TITLE
Oppia 95 edit profile

### PR DESCRIPTION
**Pull request by jbc25**

### CODE REVIEW

**Comment by alexlittle** [comment]
@jbc25 thanks for this, just something I noticed....
when I login (when online), it doesn't appear to be picking up the email address from the server. So if I have an email address in my profile on the server, then I log in on a clean install of the app, then go to edit my profile, my existing email does not appear in the email field. So then I have to re-type it to be able to submit the form successfully

**Comment by alexlittle** [comment]
I can have a look at getting this fixed up as I think there are things that nee to be done on the server side too for this

**Comment by jbc25** [comment]
I've just try the login request again and now the email field appears, but it is null (I have a valid email in my profile). 
Anyway now I can modify the code to retrieve the email field, so I'm going to create another pull request with that. (when the server is ready, it should work everything)

**Comment by alexlittle** [comment]
Sure, I'm having a look at this on the server side now - so returning the email, job_title and organisation as part of the login request

**Comment by alexlittle** [comment]
just done the pull request and tested, so seems to be working well now

**Pull request merged**
